src/Entity/Publication.php
<?php

namespace App\Entity;

use App\Repository\PublicationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PublicationRepository::class)
 */
class Publication
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */

    private $title;
    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="date")
     */
    private $date;


    /**
     * @ORM\ManyToOne(targetEntity=Classroom::class, inversedBy="publications")
     */
    private $classroom;

    /**
     * @ORM\OneToOne(targetEntity=Measure::class, inversedBy="publication", cascade={"persist", "remove"})
     */
    private $measure;

    /**
     * @ORM\Column(nullable=true)
     * @ORM\OneToMany(targetEntity=File::class, mappedBy="publication", orphanRemoval=true)
     */
    private $files;

    public function __construct()
    {
        $this->files = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @param string $title
     * @return Publication
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $content
     * @return Publication
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }



    public function getClassroom(): ?Classroom
    {
        return $this->classroom;
    }

    public function setClassroom(?Classroom $classroom): self
    {
        $this->classroom = $classroom;

        return $this;
    }

    public function getMeasure(): ?Measure
    {
        return $this->measure;
    }

    public function setMeasure(?Measure $measure): self
    {
        $this->measure = $measure;

        return $this;
    }

    /**
     * @return Collection|File[]
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file = null ): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setPublication($this);
        }

        return $this;
    }

    public function removeFile(File $file): self
    {
        if ($this->files->contains($file)) {
            $this->files->removeElement($file);
            // set the owning side to null (unless already changed)
            if ($file->getPublication() === $this) {
                $file->setPublication(null);
            }
        }

        return $this;
    }
}

src/Entity/School.php
<?php

namespace App\Entity;

use App\Repository\SchoolRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SchoolRepository::class)
 */
class School
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $State;


    /**
     * @var float
     *
     * @ORM\Column(name="latitude", type="float", scale=7, nullable=true)
     */
    private $latitude;

    /**
     * @var float
     *
     * @ORM\Column(name="longitude", type="float", scale=7, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\OneToMany(targetEntity=Classroom::class, mappedBy="school")
     */
    private $classrooms;

    public function __construct()
    {
        $this->classrooms = new ArrayCollection();
    }
    public function __toString()
    {
        return $this->Name;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->State;
    }

    public function setState(?string $State): self
    {
        $this->State = $State;

        return $this;
    }

    /**
     * @param float $longitude
     * @return User
     */
    public function setLongitude($longitude) {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * @return float
     */
    public function getLongitude() {
        return $this->longitude;
    }


    /**
     * @param float $latitude
     * @return User
     */
    public function setLatitude($latitude) {
        $this->latitude = $latitude;

        return $this;
    }

    /**
     * @return float
     */
    public function getLatitude() {
        return $this->latitude;
    }

    /**
     * @return Collection|Classroom[]
     */
    public function getClassrooms(): Collection
    {
        return $this->classrooms;
    }

    public function addClassroom(Classroom $classroom): self
    {
        if (!$this->classrooms->contains($classroom)) {
            $this->classrooms[] = $classroom;
            $classroom->setSchool($this);
        }

        return $this;
    }

    public function removeClassroom(Classroom $classroom): self
    {
        if ($this->classrooms->contains($classroom)) {
            $this->classrooms->removeElement($classroom);
            // set the owning side to null (unless already changed)
            if ($classroom->getSchool() === $this) {
                $classroom->setSchool(null);
            }
        }

        return $this;
    }
}

src/Form/PublicationType.php
<?php

namespace App\Form;

use App\Entity\Publication;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PublicationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')

            ->add('date');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Publication::class,
        ]);
    }
}

src/Controller/PublicationController.php
<?php

namespace App\Controller;

use App\Entity\Publication;
use App\Form\PublicationType;
use App\Entity\Classroom;
use App\Repository\PublicationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Knp\Component\Pager\PaginatorInterface; // Nous appelons le bundle KNP Paginator
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/publication")
 */
class PublicationController extends AbstractController
{
    /**
     * @Route("/", name="publication_index", methods={"GET"})
     */
    public function index(Request $request,PublicationRepository $publicationRepository,PaginatorInterface $paginator): Response
    {
      $publis=$publicationRepository->findBy([],['date' => 'DESC']);
      $publications = $paginator->paginate($publis,$request->query->getInt('page', 1),5);
      $nbPages = count($publis) / 5;
        return $this->render('publication/showAll.html.twig', [
            'publications' => $publications,
            'pages'=> ceil($nbPages),

        ]);



    }


    // /**
    //  * @Route("/new", name="publication_new", methods={"GET","POST"})
    //  */
    // public function new(Request $request): Response
    // {
    //     $publication = new Publication();
    //     $form = $this->createForm(PublicationType::class, $publication);
    //     $form->handleRequest($request);
    //
    //     if ($form->isSubmitted() && $form->isValid()) {
    //         $entityManager = $this->getDoctrine()->getManager();
    //         $entityManager->persist($publication);
    //         $entityManager->flush();
    //
    //         return $this->redirectToRoute('publication_index');
    //     }
    //
    //     return $this->render('publication/new.html.twig', [
    //         'publication' => $publication,
    //         'form' => $form->createView(),
    //     ]);
    // }

    /**
     * @Route("/{id}", name="publication_show", methods={"GET"})
     */
    public function show(Publication $publication): Response
    {
        return $this->render('publication/show.html.twig', [
            'publication' => $publication,
        ]);
    }

    /**
     * @Route("/class/{id}", name="publication_classe", methods={"GET"})
     */
    public function showforClass(Classroom $class,PublicationRepository $publicationRepository,$id): Response
    {
      $role=$this->getUser()->getRoles();

      $publicationClass=$publicationRepository->findBy(['classroom' => $id]);
      if($role[0] == "ROLE_TEACHER" || $role[0] == "ROLE_ADMIN"){
        return $this->render('publication/showAll.html.twig', [
            'publications' => $publicationClass,
        ]);
      }
      else {
        return $this->render('publication/showAllEleve.html.twig', [
            'publications' => $publicationClass,
        ]);
      }
    }


    /**
     * @Route("/{id}/edit", name="publication_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Publication $publication): Response
    {
        $form = $this->createForm(PublicationType::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('publication_index');
        }

        return $this->render('publication/edit.html.twig', [
            'publication' => $publication,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="publication_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Publication $publication): Response
    {
        if ($this->isCsrfTokenValid('delete'.$publication->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($publication);
            $entityManager->flush();
        }

        return $this->redirectToRoute('publication_index');
    }
}

templates/publication/_delete_form.html.twig
<form method="post" action="{{ path('publication_delete', {'id': publication.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ publication.id) }}">
    <button class="deletebtn">Delete</button>
</form>

templates/publication/bak.show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Publication{% endblock %}

{% block body %}
<div class="container" style="margin-top:35px;background-color:#c9ffd6">
<a href="{{ (app.request.headers.get('referer'))
 }}"><h6><i class="fa fa-arrow-circle-left"></i> Back</h6></a>

    <table class="table">
        <tbody>

            <tr>
                <th><h2>Title : {{ publication.title }}</h2></th>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ publication.content }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ publication.date ? publication.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Classe</th>
                <td>{{ publication.classroom}}</td>
            </tr>
            {% if publication.measure != null %}
            {% if publication.measure.temperature != null %}
            <tr>
                <th>Temperature </th>
                <td>{{ publication.measure.temperature}} °</td>
            </tr>
          {% endif %}

          {% if publication.measure.windSpeed != null %}
          <tr>
              <th>Wind speed </th>
              <td>{{ publication.measure.windSpeed}} km/h</td>
          </tr>
        {% endif %}

        {% if publication.measure.windDirection != null %}
        <tr>
            <th>Wind direction </th>
            <td>{{ publication.measure.windDirection}} °</td>
        </tr>
      {% endif %}

      {% if publication.measure.rainLevel != null %}
      <tr>
          <th>Rain level </th>
          <td>{{ publication.measure.rainLevel}} mm</td>
      </tr>
    {% endif %}
  {% endif %}
        </tbody>
    </table>
    {% set maClasse = 0 %}
  {% for classUser in app.user.classroom %}
    {% if publication.classroom.id == classUser.id %}
      {% set maClasse = maClasse + 1 %}
    {% endif %}
  {% endfor %}

    {% if is_granted('ROLE_ADMIN') or (is_granted('ROLE_TEACHER') and maClasse == 1 ) %}
    <br></br>
    <a href="{{ path('publication_edit', {'id': publication.id}) }}"><button class="newbtn"> edit </button></a>
<br></br>
    {{ include('publication/_delete_form.html.twig') }}
  {% endif %}
  </div>
{% endblock %}

templates/publication/download.html.twig
{% include 'base.html.twig' %}

{% block body %}

<div class="container">
    <div card>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <td>FileName</td>
                    <td>FileSize</td>
                    <td>Download</td>
                </tr>
                </thead>
                <tbody>
                {% for file in files %}
                <tr>
                    <td>{{ file.getName() }}</td>
                    <td>{{ file.getFileSize() }}</td>
                    <td> <a href="{{ asset('uploads/'~file.getName())}}" class="btn btn-primary btn-lg" download>Download</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
    <script>
        navigator.geolocation.getCurrentPosition(function(position) {
            faireQqc(position.coords.latitude, position.coords.longitude);
        });
    </script>
{% endblock %}

templates/publication/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Publication{% endblock %}

{% block body %}
    <h1>Edit Publication</h1>

    {{ include('publication/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('publication_index') }}">back to list</a>

    {{ include('publication/_delete_form.html.twig') }}
{% endblock %}

templates/publication/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Relevés{% endblock %}

{% block body %}
<h3>Les rélevés</h3>


</section>


{% endblock %}

templates/publication/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Publication{% endblock %}

{% block body %}
    <h1>Create new Publication</h1>

    {{ include('publication/_form.html.twig') }}

    <a href="{{ path('publication_index') }}">back to list</a>
{% endblock %}

templates/publication/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Publication{% endblock %}

{% block body %}
<div class="container" style="margin-top:35px;background-color:#c9ffd6;padding:20px;">
<a href="{{ (app.request.headers.get('referer'))
 }}"><h6><i class="fa fa-arrow-circle-left" style="color:black;font-size: 40px;"></i></h6></a>

    <table class="table">
        <tbody>

            <tr>
                <th><h2>Title : {{ publication.title }}</h2></th>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ publication.content }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ publication.date ? publication.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Classe</th>
                <td>{{ publication.classroom}}</td>
            </tr>
            {% if publication.measure != null %}
            {% if publication.measure.temperature != null %}
            <tr>
                <th>Temperature </th>
                <td>{{ publication.measure.temperature}} °</td>
            </tr>
          {% endif %}

          {% if publication.measure.windSpeed != null %}
          <tr>
              <th>Wind speed </th>
              <td>{{ publication.measure.windSpeed}} km/h</td>
          </tr>
        {% endif %}

        {% if publication.measure.windDirection != null %}
        <tr>
            <th>Wind direction </th>
            <td>{{ publication.measure.windDirection}} °</td>
        </tr>
      {% endif %}

      {% if publication.measure.rainLevel != null %}
      <tr>
          <th>Rain level </th>
          <td>{{ publication.measure.rainLevel}} mm</td>
      </tr>
    {% endif %}
  {% endif %}
        </tbody>
    </table>
    {% set maClasse = 0 %}
  {% for classUser in app.user.classroom %}
    {% if publication.classroom.id == classUser.id %}
      {% set maClasse = maClasse + 1 %}
    {% endif %}
  {% endfor %}

    {% if is_granted('ROLE_ADMIN') or (is_granted('ROLE_TEACHER') and maClasse == 1 ) %}
    <br></br>
    <a href="{{ path('publication_edit', {'id': publication.id}) }}"><button class="newbtn"> edit </button></a>
<br></br>
    {{ include('publication/_delete_form.html.twig') }}
  {% endif %}
  </div>
{% endblock %}

templates/publication/showAll.html.twig
{% extends 'base.html.twig' %}

{% block title %}Publication index{% endblock %}

{% block body %}

    <h3 class="titleH3">Publications</h3>
    <div style="display:flex; justify-content:flex-end;margin-right:210px;margin-bottom:40px;">
    <a href="{{ path('new_publication') }}"><button class="btn btn-success" style="width: 180px;
    height: 50px;text-transform: uppercase;padding:5px;" >New publication <i class="fa fa-plus-circle" style=""></i>
    </div>
 </button></a>



        {% for publication in publications  %}
            <div class="container ">
            <div class="card tabPublication" style="padding:20px;background-color:#d6f9e6;">
            <h3 class="card-title" style="text-align:center;">  <a href="{{ path('publication_show', {'id': publication.id}) }}">{{ publication.title }}</a> </h3>
              <div class="card-body">
              <p>{{publication.classroom}}</p>
              <b style="color:#323332;">{{ publication.content }}</b>
              <br></br>
              <hr></hr>
              {% if publication.classroom != null %}
              <h5 class="card-subtitle mb-2 text-muted"><i class="fa fa-map-marker" aria-hidden="true"></i> {{ publication.classroom.school.city}} ({{publication.classroom.school.state}})</h5>
            {% endif %}
              <h6 class="card-subtitle mb-2 text-muted">{{ publication.date ? publication.date|date('Y-m-d') : '' }}</h6>
              <a href="{{ path('publication_show', {'id': publication.id}) }}" style="text-align:right;"><button class="newbtn">See more</button> </a>
              </div>
            </div>
            </div>

        {% endfor %}
        <div style="display:flex;justify-content:center;">
        {% if app.request.query.get("page") == 1 %}
          <i class="fa fa-arrow-circle-left fa-10x" style="color:grey"></i>

        {% else %}
          <a href="{{path ('publication_index', {'page': app.request.query.get("page") - 1})}}"><i class="fa fa-arrow-circle-left fa-10x"></i></a>

        {% endif %}
          <h6 style="margin-top:20px;">{{app.request.query.get("page")}} / {{pages}}</h6>
        {% if app.request.query.get("page") == pages %}
        <i class="fa fa-arrow-circle-right fa-10x" style="color:grey"></i>

        {% else %}
          <a href="{{path ('publication_index', {'page': app.request.query.get("page") + 1})}}"><i class="fa fa-arrow-circle-right fa-10x"></i></a>
        {% endif %}


        </div>

{% endblock %}

templates/publication/showAllEleve.html.twig
{% extends 'base.html.twig' %}

{% block title %}Publication index{% endblock %}

{% block body %}
    <h1>Publication index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Content</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for publication in publications|sort((a, b) => a.date <=> b.date) %}
            <tr>
                <td><a href="{{ path('publication_show', {'id': publication.id}) }}">{{ publication.title }}</a></td>
                <td><a href="{{ path('publication_show', {'id': publication.id}) }}">{{ publication.content }}</a></td>
                <td>{{ publication.date ? publication.date|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('publication_show', {'id': publication.id}) }}">voir le relevé</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">pas de relevé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}